# Arrays and vector processing

In [3]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

print(type(my_arr), '<- my_arr')
print(type(my_list), '<- my_list')

%time for _ in range(10): my_arr2 = my_arr * 2

%time for _ in range(10): my_list2 = [x * 2 for x in my_list]


<class 'numpy.ndarray'> <- my_arr
<class 'list'> <- my_list
CPU times: user 12.5 ms, sys: 12 ms, total: 24.5 ms
Wall time: 25 ms
CPU times: user 799 ms, sys: 128 ms, total: 927 ms
Wall time: 927 ms


##### NumPy's ndarray: A multidimensional object

*Mathematical Operations in Blocks*

In [20]:
import numpy as np

#Array of random data
data = np.random.randn(2, 3)
print(data, '<- data_raw')

data_multiplied_for_10 = data * 10
print(data_multiplied_for_10, '<- multiplied for 10')

data_added_for_10 = data + 10
print(data_added_for_10, '<- added 10')

print(data.shape)
print(data.dtype)
print(type(data))
print(data.dtype)


[[-0.30695411  1.23452821  0.08929974]
 [ 1.94556712 -0.43770656  0.42619785]] <- data_raw
[[-3.0695411  12.34528213  0.89299737]
 [19.4556712  -4.37706559  4.26197855]] <- multiplied for 10
[[ 9.69304589 11.23452821 10.08929974]
 [11.94556712  9.56229344 10.42619785]] <- added 10
(2, 3)
float64
<class 'numpy.ndarray'>
float64


##### Creating arrays

*Function np.array()*

In [22]:
data1 = [6, 7.5, 8, 0, 1]

arr1 = np.array(data1)

arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [23]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

arr2 = np.array(data2)

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
print(arr2.ndim, '<- arr2')
print(arr2.shape, '<- arr2')

print(arr1.dtype, '<- arr1')
print(arr2.dtype, '<- arr2')

2 <- arr2
(2, 4) <- arr2
float64 <- arr1
int64 <- arr2


##### Method zeros, ones and empty

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

*Pass a tuple to arrays with larger dimensions*

In [34]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [42]:
np.empty((2, 3, 2))

array([[[4.67980513e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [2.12199579e-313, 2.21468802e-052]],

       [[1.53356532e-075, 2.19209875e-056],
        [4.31875102e-061, 7.96528258e-042],
        [1.54767774e+185, 1.82992025e-076]]])

*Method np.range()*

In [4]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

*Data type for ndarrays*

In [7]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

arr2 = np.array([1, 2, 3], dtype=np.int32)

arr2.dtype

dtype('int32')

*Conversion and casting*

In [10]:
arr = np.array([1, 2, 3, 4, 5])

print(arr.dtype)

float_arr = arr.astype(np.float64)

float_arr.dtype

int64


dtype('float64')

*Conversion to int will truncate*

In [13]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

print(arr)

arr.astype(np.int32)

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]


array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [21]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

print(numeric_strings)

numeric_strings.astype(float)

[b'1.25' b'-9.6' b'42']


array([ 1.25, -9.6 , 42.  ])

*Using dttype from another array*

In [22]:
int_array = np.arange(10)

calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [27]:
empty_uint32 = np.empty(8, dtype='u4')

empty_uint32

array([1445773375,      22064,          0,          0,  901173760,
            22069,  897454496,      22069], dtype=uint32)

##### Arithmetic with NumPy Arrays

*Any arithmetic operation between arrays of the same size causes the operation to be applied to all elements.*

In [7]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

print(arr)

print(arr * arr)

print(arr - arr)

print(1 / arr)

arr ** 0.5

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

*Comparisons between arrays of the same size result in boolean arrays*

In [8]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12]])

print(arr2)

arr2 > arr

[[ 0.  4.  1.]
 [ 7.  2. 12.]]


array([[False,  True, False],
       [ True, False,  True]])

##### Indexing and slicing

*One-dimensional arrays are simple, superficially they behave similar to Python lists*

In [12]:
arr = np.arange(10)

print(arr)

print(arr[5])

print(arr[5:8])

arr[5:8] = 12

arr

arr_slice = arr[5:8]

print(arr_slice)

arr_slice[1] = 12345

print(arr)

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[12 12 12]
[    0     1     2     3     4    12 12345    12     8     9]


*The bare slice [:] will do an assignment to all values ​​in an array*

In [15]:
arr_slice[:] = 64

arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

*Copying arrays*

In [12]:
arr_copy = arr[4:7].copy()

print(arr_copy)

arr_copy[:] = 10

print(arr_copy)

arr[4:7]

[ 4 64 64]
[10 10 10]


array([ 4, 64, 64])

*Larger dimensional arrays*

In [5]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr2d[2])

print(arr2d[0][2])
print(arr2d[0, 2])

[7 8 9]
3
3


In [9]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [32]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

*Both scalar and array values ​​can be assigned to arr3d[0]*

In [10]:
old_values = arr3d[0].copy()

arr3d[0] = 42

arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [37]:
arr3d[0] = old_values

arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

*arr3d[1, 0] contains all values ​​whose indices start with (0, 1), forming a one-dimensional array*

In [38]:
arr3d[1, 0]

array([7, 8, 9])

*This expression is equivalent to a two-step indexing*

In [41]:
x = arr3d[1]

print(x)

print(x[0])

[[ 7  8  9]
 [10 11 12]]
[7 8 9]


*Indexing with slices*

In [16]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [17]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

*Slicing an array2d is a little different*

In [18]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

*We can pass multiple slices, just as we can pass multiple indexes*

In [24]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [27]:
arr2d[1, :2]

array([4, 5])

In [28]:
arr2d[:2, 2]

array([3, 6])

*Slice higher dimension axes*

In [30]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [34]:
arr2d[:2, 1:] = 0

arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [35]:
arr2d(2, 2)

TypeError: 'numpy.ndarray' object is not callable