# Arrays and vector processing

In [39]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

print(type(my_arr), '<- my_arr')
print(type(my_list), '<- my_list')

%time for _ in range(10): my_arr2 = my_arr * 2

%time for _ in range(10): my_list2 = [x * 2 for x in my_list]


<class 'numpy.ndarray'> <- my_arr
<class 'list'> <- my_list
CPU times: user 14.6 ms, sys: 4.48 ms, total: 19 ms
Wall time: 19.2 ms
CPU times: user 731 ms, sys: 91.4 ms, total: 822 ms
Wall time: 863 ms


##### NumPy's ndarray: A multidimensional object

*Mathematical Operations in Blocks*

In [40]:
import numpy as np

#Array of random data
data = np.random.randn(2, 3)
print(data, '<- data_raw')

data_multiplied_for_10 = data * 10
print(data_multiplied_for_10, '<- multiplied for 10')

data_added_for_10 = data + 10
print(data_added_for_10, '<- added 10')

print(data.shape)
print(data.dtype)
print(type(data))
print(data.dtype)


[[-0.69471786  0.05710201  2.9263098 ]
 [ 0.25349346 -0.75254405 -0.15530011]] <- data_raw
[[-6.94717859  0.57102009 29.263098  ]
 [ 2.5349346  -7.52544054 -1.55300105]] <- multiplied for 10
[[ 9.30528214 10.05710201 12.9263098 ]
 [10.25349346  9.24745595  9.84469989]] <- added 10
(2, 3)
float64
<class 'numpy.ndarray'>
float64


##### Creating arrays

*Function np.array()*

In [41]:
data1 = [6, 7.5, 8, 0, 1]

arr1 = np.array(data1)

arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [42]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

arr2 = np.array(data2)

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [43]:
print(arr2.ndim, '<- arr2')
print(arr2.shape, '<- arr2')

print(arr1.dtype, '<- arr1')
print(arr2.dtype, '<- arr2')

2 <- arr2
(2, 4) <- arr2
float64 <- arr1
int64 <- arr2


##### Method zeros, ones and empty

In [44]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

*Pass a tuple to arrays with larger dimensions*

In [45]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [46]:
np.empty((2, 3, 2))

array([[[4.64834879e-310, 0.00000000e+000],
        [1.01855798e-312, 9.54898106e-313],
        [1.18831764e-312, 1.01855798e-312]],

       [[1.23075756e-312, 1.10343781e-312],
        [1.03977794e-312, 9.76118064e-313],
        [1.03977794e-312, 1.90979621e-312]]])

*Method np.range()*

In [47]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

*Data type for ndarrays*

In [48]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

arr2 = np.array([1, 2, 3], dtype=np.int32)

arr2.dtype

dtype('int32')

*Conversion and casting*

In [49]:
arr = np.array([1, 2, 3, 4, 5])

print(arr.dtype)

float_arr = arr.astype(np.float64)

float_arr.dtype

int64


dtype('float64')

*Conversion to int will truncate*

In [50]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

print(arr)

arr.astype(np.int32)

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]


array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [51]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

print(numeric_strings)

numeric_strings.astype(float)

[b'1.25' b'-9.6' b'42']


array([ 1.25, -9.6 , 42.  ])

*Using dttype from another array*

In [52]:
int_array = np.arange(10)

calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [53]:
empty_uint32 = np.empty(8, dtype='u4')

empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

##### Arithmetic with NumPy Arrays

*Any arithmetic operation between arrays of the same size causes the operation to be applied to all elements.*

In [54]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

print(arr)

print(arr * arr)

print(arr - arr)

print(1 / arr)

arr ** 0.5

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

*Comparisons between arrays of the same size result in boolean arrays*

In [55]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12]])

print(arr2)

arr2 > arr

[[ 0.  4.  1.]
 [ 7.  2. 12.]]


array([[False,  True, False],
       [ True, False,  True]])

##### Indexing and slicing

*One-dimensional arrays are simple, superficially they behave similar to Python lists*

In [56]:
arr = np.arange(10)

print(arr)

print(arr[5])

print(arr[5:8])

arr[5:8] = 12

arr

arr_slice = arr[5:8]

print(arr_slice)

arr_slice[1] = 12345

print(arr)

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[12 12 12]
[    0     1     2     3     4    12 12345    12     8     9]


*The bare slice [:] will do an assignment to all values ​​in an array*

In [57]:
arr_slice[:] = 64

arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

*Copying arrays*

In [58]:
arr_copy = arr[4:7].copy()

print(arr_copy)

arr_copy[:] = 10

print(arr_copy)

arr[4:7]

[ 4 64 64]
[10 10 10]


array([ 4, 64, 64])

*Larger dimensional arrays*

In [59]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr2d[2])

print(arr2d[0][2])
print(arr2d[0, 2])

[7 8 9]
3
3


In [60]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [61]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

*Both scalar and array values ​​can be assigned to arr3d[0]*

In [62]:
old_values = arr3d[0].copy()

arr3d[0] = 42

arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [63]:
arr3d[0] = old_values

arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

*arr3d[1, 0] contains all values ​​whose indices start with (0, 1), forming a one-dimensional array*

In [64]:
arr3d[1, 0]

array([7, 8, 9])

*This expression is equivalent to a two-step indexing*

In [65]:
x = arr3d[1]

print(x)

print(x[0])

[[ 7  8  9]
 [10 11 12]]
[7 8 9]


*Indexing with slices*

In [66]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [67]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

*Slicing an array2d is a little different*

In [68]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

*We can pass multiple slices, just as we can pass multiple indexes*

In [70]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [71]:
arr2d[1, :2]

array([4, 5])

In [72]:
arr2d[:2, 2]

array([3, 6])

*Slice higher dimension axes*

In [73]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [74]:
arr2d[:2, 1:] = 0

arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [75]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

data = np.random.randn(7, 4)

names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [76]:
data

array([[-1.83022766e+00, -2.19843166e-01, -1.33088514e+00,
        -7.33275646e-01],
       [ 1.87303069e-01,  2.18791282e-03, -4.61345374e-02,
        -2.03909841e+00],
       [ 8.06442111e-01,  3.63999422e-01,  2.20761974e+00,
        -1.33537055e+00],
       [ 1.88504010e+00,  3.64451478e-01, -1.39166395e+00,
        -1.09763223e+00],
       [-1.09412361e+00,  9.72653248e-01, -8.68886392e-02,
        -1.07590664e-01],
       [ 1.57048452e+00,  1.27702001e+00,  8.47311478e-01,
         6.90758415e-02],
       [-1.59985557e+00, -5.57189165e-01, -8.36239671e-01,
         3.07018814e-02]])

In [77]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [78]:
data[names == 'Bob']

array([[-1.83022766, -0.21984317, -1.33088514, -0.73327565],
       [ 1.8850401 ,  0.36445148, -1.39166395, -1.09763223]])

*Indexing columns*

In [79]:
data[names == 'Bob', 2:]

array([[-1.33088514, -0.73327565],
       [-1.39166395, -1.09763223]])

In [80]:
data[names == 'Bob', 3]

array([-0.73327565, -1.09763223])

*Select everything except Bob*

In [81]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

*Using the ~ operator to negate the condition*

In [82]:
data[~(names == 'Bob')]

array([[ 1.87303069e-01,  2.18791282e-03, -4.61345374e-02,
        -2.03909841e+00],
       [ 8.06442111e-01,  3.63999422e-01,  2.20761974e+00,
        -1.33537055e+00],
       [-1.09412361e+00,  9.72653248e-01, -8.68886392e-02,
        -1.07590664e-01],
       [ 1.57048452e+00,  1.27702001e+00,  8.47311478e-01,
         6.90758415e-02],
       [-1.59985557e+00, -5.57189165e-01, -8.36239671e-01,
         3.07018814e-02]])

*The ~ operator can be useful when we want to invert a generic condition*

In [83]:
cond = names == 'Bob'

data[~cond]

array([[ 1.87303069e-01,  2.18791282e-03, -4.61345374e-02,
        -2.03909841e+00],
       [ 8.06442111e-01,  3.63999422e-01,  2.20761974e+00,
        -1.33537055e+00],
       [-1.09412361e+00,  9.72653248e-01, -8.68886392e-02,
        -1.07590664e-01],
       [ 1.57048452e+00,  1.27702001e+00,  8.47311478e-01,
         6.90758415e-02],
       [-1.59985557e+00, -5.57189165e-01, -8.36239671e-01,
         3.07018814e-02]])

*To select two of the three names to match multiple Boolean conditions, use Boolean arithmetic operators such as & (and) and | (or)*

In [84]:
mask = (names == 'Bob' ) | (names == 'Will')

mask

array([ True, False,  True,  True,  True, False, False])

In [85]:
data[mask]

array([[-1.83022766, -0.21984317, -1.33088514, -0.73327565],
       [ 0.80644211,  0.36399942,  2.20761974, -1.33537055],
       [ 1.8850401 ,  0.36445148, -1.39166395, -1.09763223],
       [-1.09412361,  0.97265325, -0.08688864, -0.10759066]])

*Setting values ​​with boolean arrays*

*To set all negative values ​​in data to 0, just do the following*

In [87]:
data[data < 0] = 0

data

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.87303069e-01, 2.18791282e-03, 0.00000000e+00, 0.00000000e+00],
       [8.06442111e-01, 3.63999422e-01, 2.20761974e+00, 0.00000000e+00],
       [1.88504010e+00, 3.64451478e-01, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 9.72653248e-01, 0.00000000e+00, 0.00000000e+00],
       [1.57048452e+00, 1.27702001e+00, 8.47311478e-01, 6.90758415e-02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.07018814e-02]])

*Defining entire rows or columns using a one-dimensional Boolean array is also easy*

In [88]:
data[names != 'Joe'] = 7

data

array([[7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [1.87303069e-01, 2.18791282e-03, 0.00000000e+00, 0.00000000e+00],
       [7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [7.00000000e+00, 7.00000000e+00, 7.00000000e+00, 7.00000000e+00],
       [1.57048452e+00, 1.27702001e+00, 8.47311478e-01, 6.90758415e-02],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.07018814e-02]])