# Arrays and vector processing

In [3]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

print(type(my_arr), '<- my_arr')
print(type(my_list), '<- my_list')

%time for _ in range(10): my_arr2 = my_arr * 2

%time for _ in range(10): my_list2 = [x * 2 for x in my_list]


<class 'numpy.ndarray'> <- my_arr
<class 'list'> <- my_list
CPU times: user 25.6 ms, sys: 1.22 ms, total: 26.8 ms
Wall time: 27.2 ms
CPU times: user 762 ms, sys: 89.4 ms, total: 852 ms
Wall time: 852 ms


##### NumPy's ndarray: A multidimensional object

*Mathematical Operations in Blocks*

In [20]:
import numpy as np

#Array of random data
data = np.random.randn(2, 3)
print(data, '<- data_raw')

data_multiplied_for_10 = data * 10
print(data_multiplied_for_10, '<- multiplied for 10')

data_added_for_10 = data + 10
print(data_added_for_10, '<- added 10')

print(data.shape)
print(data.dtype)
print(type(data))
print(data.dtype)


[[-0.30695411  1.23452821  0.08929974]
 [ 1.94556712 -0.43770656  0.42619785]] <- data_raw
[[-3.0695411  12.34528213  0.89299737]
 [19.4556712  -4.37706559  4.26197855]] <- multiplied for 10
[[ 9.69304589 11.23452821 10.08929974]
 [11.94556712  9.56229344 10.42619785]] <- added 10
(2, 3)
float64
<class 'numpy.ndarray'>
float64


##### Creating arrays

*Function np.array()*

In [22]:
data1 = [6, 7.5, 8, 0, 1]

arr1 = np.array(data1)

arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [23]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

arr2 = np.array(data2)

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
print(arr2.ndim, '<- arr2')
print(arr2.shape, '<- arr2')

print(arr1.dtype, '<- arr1')
print(arr2.dtype, '<- arr2')

2 <- arr2
(2, 4) <- arr2
float64 <- arr1
int64 <- arr2


##### Method zeros, ones and empty

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

*Pass a tuple to arrays with larger dimensions*

In [34]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [42]:
np.empty((2, 3, 2))

array([[[4.67980513e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [2.12199579e-313, 2.21468802e-052]],

       [[1.53356532e-075, 2.19209875e-056],
        [4.31875102e-061, 7.96528258e-042],
        [1.54767774e+185, 1.82992025e-076]]])

*Method np.range()*

In [4]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

*Data type for ndarrays*

In [7]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

arr2 = np.array([1, 2, 3], dtype=np.int32)

arr2.dtype

dtype('int32')

*Conversion and casting*

In [10]:
arr = np.array([1, 2, 3, 4, 5])

print(arr.dtype)

float_arr = arr.astype(np.float64)

float_arr.dtype

int64


dtype('float64')

*Conversion to int will truncate*

In [13]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

print(arr)

arr.astype(np.int32)

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]


array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [21]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

print(numeric_strings)

numeric_strings.astype(float)

[b'1.25' b'-9.6' b'42']


array([ 1.25, -9.6 , 42.  ])

*Using dttype from another array*

In [22]:
int_array = np.arange(10)

calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [27]:
empty_uint32 = np.empty(8, dtype='u4')

empty_uint32

array([1445773375,      22064,          0,          0,  901173760,
            22069,  897454496,      22069], dtype=uint32)

##### Arithmetic with NumPy Arrays

*Any arithmetic operation between arrays of the same size causes the operation to be applied to all elements.*

In [34]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

print(arr)

print(arr * arr)

print(arr - arr)

print(1 / arr)

arr ** 0.5

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

*Comparisons between arrays of the same size result in boolean arrays*

In [37]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12]])

print(arr2)

arr2 > arr

[[ 0.  4.  1.]
 [ 7.  2. 12.]]


array([[False,  True, False],
       [ True, False,  True]])